parameters:
#    igor_test.example.class: Igor\TestBundle\Example

services:
#    igor_test.example:
#        class: %igor_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
